/**
 * generated by Xtext 2.13.0
 */
package org.xtext.distj14.ui.contentassist;

import org.xtext.distj14.ui.contentassist.AbstractMathProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class MathProposalProvider extends AbstractMathProposalProvider {
}
