/*
 * generated by Xtext 2.13.0
 */
package org.xtext.distj14.ui.tests;

import com.google.inject.Injector;
import distj14Math.ui.internal.Distj14MathActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class MathUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Distj14MathActivator.getInstance().getInjector("org.xtext.distj14.Math");
	}

}
