/**
 * generated by Xtext 2.13.0
 */
package org.xtext.distj14.ide;

import org.xtext.distj14.ide.AbstractMathIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class MathIdeModule extends AbstractMathIdeModule {
}
