/**
 * generated by Xtext 2.13.0
 */
package org.xtext.distj14.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.distj14.MathRuntimeModule;
import org.xtext.distj14.MathStandaloneSetup;
import org.xtext.distj14.ide.MathIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class MathIdeSetup extends MathStandaloneSetup {
  @Override
  public Injector createInjector() {
    MathRuntimeModule _mathRuntimeModule = new MathRuntimeModule();
    MathIdeModule _mathIdeModule = new MathIdeModule();
    return Guice.createInjector(Modules2.mixin(_mathRuntimeModule, _mathIdeModule));
  }
}
