/**
 * generated by Xtext 2.13.0
 */
package org.xtext.distj14.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.distj14.ui.AbstractMathUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class MathUiModule extends AbstractMathUiModule {
  public MathUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
