/*
 * generated by Xtext 2.13.0
 */
package org.xtext.distj14.ui;

import com.google.inject.Injector;
import distj14Math.ui.internal.Distj14MathActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MathExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(Distj14MathActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		Distj14MathActivator activator = Distj14MathActivator.getInstance();
		return activator != null ? activator.getInjector(Distj14MathActivator.ORG_XTEXT_DISTJ14_MATH) : null;
	}

}
