/*
 * generated by Xtext 2.13.0
 */
package org.xtext.distj14.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.xtext.distj14.MathRuntimeModule
import org.xtext.distj14.MathStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class MathIdeSetup extends MathStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new MathRuntimeModule, new MathIdeModule))
	}
	
}
